apiVersion: skaffold/v2beta28
kind: Config
build:
  tagPolicy:
    sha256: {}
#    gitCommit: {}
  artifacts:
    - image: harbor.bk.rfios.com/ruoyi-k8s/ruoyi-ui
      context: ./ruoyi-ui/
#    - image: harbor.bk.rfios.com/ruoyi-k8s/ruoyi-gateway
#      context: ./ruoyi-gateway/
    - image: harbor.bk.rfios.com/ruoyi-k8s/ruoyi-auth
      context: ./ruoyi-auth
    - image: harbor.bk.rfios.com/ruoyi-k8s/ruoyi-modules-system
      context: ./ruoyi-modules/ruoyi-system/
    - image: harbor.bk.rfios.com/ruoyi-k8s/ruoyi-modules-job
      context: ./ruoyi-modules/ruoyi-job/
    - image: harbor.bk.rfios.com/ruoyi-k8s/ruoyi-modules-gen
      context: ./ruoyi-modules/ruoyi-gen/
    - image: harbor.bk.rfios.com/ruoyi-k8s/ruoyi-modules-file
      context: ./ruoyi-modules/ruoyi-file/
#    - image: harbor.bk.rfios.com/ruoyi-k8s/ruoyi-visual-monitor
#      context: ./ruoyi-visual/ruoyi-monitor/




deploy:
  kubectl:
    manifests:
      #- ./k8s/*.yaml
#      - ./k8s/grafana.yaml
#      - ./k8s/prometheus.yaml
      - ./k8s/gateway.yaml
      - ./k8s/gateway-auth-filter.yaml
      - ./ruoyi-ui/deploy/*.yaml
#      - ./ruoyi-gateway/deploy/*.yaml
      - ./ruoyi-auth/deploy/*.yaml
      - ./ruoyi-modules/ruoyi-system/deploy/*.yaml
      - ./ruoyi-modules/ruoyi-job/deploy/*.yaml
      - ./ruoyi-modules/ruoyi-gen/deploy/*.yaml
      - ./ruoyi-modules/ruoyi-file/deploy/*.yaml
#      - ./ruoyi-visual/ruoyi-monitor/deploy/*.yaml