apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ruoyi-monitor
  name: ruoyi-monitor
  namespace: ruoyi-k8s   #一定要写名称空间
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-monitor
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ruoyi-monitor
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - image: harbor.bk.rfios.com/ruoyi-k8s/ruoyi-visual-monitor:latest
 #         readinessProbe:
 #           httpGet:
 #             path: /actuator/health
 #             port: 8080
 #           timeoutSeconds: 10
 #           failureThreshold: 30
 #           periodSeconds: 5
          imagePullPolicy: IfNotPresent
          name: app
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Shanghai
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: ruoyi-admin
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ruoyi-monitor
  name: ruoyi-monitor
  namespace: ruoyi-k8s
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: ruoyi-monitor
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ruoyi-monitor
  namespace: ruoyi-k8s
  labels:
    spring.cloud.kubernetes.config: "true"
data:
  application.yml: |-
    spring:
      security:
        user:
          name: ruoyi
          password: 123456
      boot:
        admin:
          ui:
            title: 若依服务状态监控
        
        
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        restart:
          enabled: true
