apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ruoyi-gateway
  name: ruoyi-gateway
  namespace: ruoyi-k8s   #一定要写名称空间
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-gateway
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ruoyi-gateway
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - image: harbor.bk.rfios.com/ruoyi-k8s/ruoyi-gateway:latest
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            timeoutSeconds: 10
#            failureThreshold: 30
#            periodSeconds: 5
          imagePullPolicy: IfNotPresent
          name: app
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          ports:
            - containerPort: 80
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: ruoyi-admin
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ruoyi-gateway
  name: ruoyi-gateway
  namespace: ruoyi-k8s
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: ruoyi-gateway
  sessionAffinity: None
  type: ClusterIP

---


apiVersion: v1
kind: ConfigMap
metadata:
  name: ruoyi-gateway
  namespace: ruoyi-k8s
  labels:
    spring.cloud.kubernetes.config: "true"
data:
  application.yml: |-
    spring:
      redis:
        host: 172.16.84.18
        port: 31535
        password: '@WSX3edc'
      cloud:
        gateway:
          discovery:
            locator:
              lowerCaseServiceId: true
              enabled: true
              url-expression: "'http://'+serviceId"
          routes:
            # 认证中心
            - id: ruoyi-auth
              uri: lb://ruoyi-auth
              predicates:
                - Path=/auth/**
              filters:
                # 验证码处理
                - CacheRequestFilter
                - ValidateCodeFilter
                - StripPrefix=1
            # 代码生成
            - id: ruoyi-gen
              uri: lb://ruoyi-gen
              predicates:
                - Path=/code/**
              filters:
                - StripPrefix=1
            # 定时任务
            - id: ruoyi-job
              uri: lb://ruoyi-job
              predicates:
                - Path=/schedule/**
              filters:
                - StripPrefix=1
            # 系统模块
            - id: ruoyi-system
              uri: lb://ruoyi-system
              predicates:
                - Path=/system/**
              filters:
                - StripPrefix=1
            # 文件服务
            - id: ruoyi-file
              uri: lb://ruoyi-file
              predicates:
                - Path=/file/**
              filters:
                - StripPrefix=1
    
    # 安全配置
    security:
      # 验证码
      captcha:
        enabled: true
        type: math
      # 防止XSS攻击
      xss:
        enabled: true
        excludeUrls:
          - /system/notice
      # 不校验白名单
      ignore:
        whites:
          - /auth/logout
          - /auth/login
          - /auth/register
          - /*/v2/api-docs
          - /csrf
    logging:
      level:
        org.springframework.cloud.gateway: TRACE
        org.springframework.cloud.loadbalancer: TRACE
    
    management:
      endpoints:
        web:
          exposure:
            include: "*"
        health:
          enabled: true
        restart:
          enabled: true
        info:
          enabled: true
      endpoint:
        restart:
          enabled: true
      
            
