apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ruoyi-auth
  name: ruoyi-auth
  namespace: ruoyi-k8s   #一定要写名称空间
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-auth
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ruoyi-auth
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - image: harbor.bk.rfios.com/ruoyi-k8s/ruoyi-auth:latest
 #         readinessProbe:
 #           httpGet:
 #             path: /actuator/health
 #             port: 8080
 #           timeoutSeconds: 10
 #           failureThreshold: 30
 #           periodSeconds: 5
          imagePullPolicy: IfNotPresent
          name: app
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: ruoyi-admin
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ruoyi-auth
  name: ruoyi-auth
  namespace: ruoyi-k8s
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ruoyi-auth
  sessionAffinity: None
  type: ClusterIP
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ruoyi-auth
  namespace: ruoyi-k8s
  labels:
    spring.cloud.kubernetes.config: "true"
data:
  application.yml: |-
    server:
      port: 8080
    # Spring
    spring:
      application:
        # 应用名称
        name: ruoyi-auth
      profiles:
        # 环境配置
        active: dev
      redis:
        host: 172.16.84.18
        port: 31535
        password: '@WSX3edc'
        
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        restart:
          enabled: true
          
