apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ruoyi-admin-role
  namespace: ruoyi-k8s
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - endpoints
      - services
      - nodes
      - nodes/proxy
      - pods
      - configmaps
    verbs:
      - list
      - get
      - watch

